name = "tg-tagauto"
main = "src/worker.ts"
compatibility_date = "2026-04-05"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Counter"]

[observability.logs]
enabled = true
